config/routes.rb
Rails.application.routes.draw do
  resources :areas do
    member do
      get :poltronas_disponiveis
    end
  end

  resources :ingressos do
    collection do
      get :estatistica
    end
  end
  
  get 'ingressos/es'
  resources :clientes
  root "pecas#index"

  resources :usuarios
  resources :pecas, path: "pecas"
  resources :sessoes, path: "sessoes"
  resources :poltronas, path: "poltronas"
  resources :ingressos, path: "ingressos"
end

app/models/poltrona.rb
class Poltrona < ApplicationRecord
  belongs_to :area, optional: true
end

app/controllers/poltronas_controller.rb
class PoltronasController < ApplicationController
  before_action :set_poltrona, only: %i[ show edit update destroy ]

  # GET /poltronas or /poltronas.json
  def index
    @poltronas = Poltrona.all
  end

  # GET /poltronas/1 or /poltronas/1.json
  def show
  end

  # GET /poltronas/new
  def new
    @poltrona = Poltrona.new
  end

  # GET /poltronas/1/edit
  def edit
  end

  # POST /poltronas or /poltronas.json
  def create
    @poltrona = Poltrona.new(poltrona_params)

    respond_to do |format|
      if @poltrona.save
        format.html { redirect_to @poltrona, notice: "Poltrona was successfully created." }
        format.json { render :show, status: :created, location: @poltrona }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @poltrona.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /poltronas/1 or /poltronas/1.json
  def update
    respond_to do |format|
      if @poltrona.update(poltrona_params)
        format.html { redirect_to @poltrona, notice: "Poltrona was successfully updated." }
        format.json { render :show, status: :ok, location: @poltrona }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @poltrona.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /poltronas/1 or /poltronas/1.json
  def destroy
    @poltrona.destroy!

    respond_to do |format|
      format.html { redirect_to poltronas_path, status: :see_other, notice: "Poltrona was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_poltrona
      @poltrona = Poltrona.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def poltrona_params
      params.expect(poltrona: [ :area_id, :numero, :disponivel ])
    end
end

app/helpers/poltronas_helper.rb
module PoltronasHelper
end

app/views/poltronas/_form.html.erb
<%= form_with(model: poltrona) do |form| %>
  <% if poltrona.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(poltrona.errors.count, "error") %> prohibited this poltrona from being saved:</h2>

      <ul>
        <% poltrona.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :area_id, style: "display: block" %>
    <%= form.text_field :area_id %>
  </div>

  <div>
    <%= form.label :numero, style: "display: block" %>
    <%= form.text_field :numero %>
  </div>

  <div>
    <%= form.label :disponivel, style: "display: block" %>
    <%= form.checkbox :disponivel %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/poltronas/_poltrona.html.erb
<div id="<%= dom_id poltrona %>">
  <p>
    <strong>Area:</strong>
    <%= poltrona.area_id %>
  </p>

  <p>
    <strong>Numero:</strong>
    <%= poltrona.numero %>
  </p>

  <p>
    <strong>Disponivel:</strong>
    <%= poltrona.disponivel %>
  </p>

</div>

app/views/poltronas/edit.html.erb
<% content_for :title, "Editing poltrona" %>

<h1>Editing poltrona</h1>

<%= render "form", poltrona: @poltrona %>

<br>

<div>
  <%= link_to "Show this poltrona", @poltrona %> |
  <%= link_to "Back to poltronas", poltronas_path %>
</div>

app/views/poltronas/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Poltronas" %>

<h1>Poltronas</h1>

<div id="poltronas">
  <% @poltronas.each do |poltrona| %>
    <%= render poltrona %>
    <p>
      <%= link_to "Show this poltrona", poltrona %>
    </p>
  <% end %>
</div>

<%= link_to "New poltrona", new_poltrona_path %>

app/views/poltronas/new.html.erb
<% content_for :title, "New poltrona" %>

<h1>New poltrona</h1>

<%= render "form", poltrona: @poltrona %>

<br>

<div>
  <%= link_to "Back to poltronas", poltronas_path %>
</div>

app/views/poltronas/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @poltrona %>

<div>
  <%= link_to "Edit this poltrona", edit_poltrona_path(@poltrona) %> |
  <%= link_to "Back to poltronas", poltronas_path %>

  <%= button_to "Destroy this poltrona", @poltrona, method: :delete %>
</div>