config/routes.rb
Rails.application.routes.draw do
  resources :areas do
    member do
      get :poltronas_disponiveis
    end
  end

  resources :ingressos do
    collection do
      get :estatistica
    end
  end
  
  get 'ingressos/es'
  resources :clientes
  root "pecas#index"

  resources :usuarios
  resources :pecas, path: "pecas"
  resources :sessoes, path: "sessoes"
  resources :poltronas, path: "poltronas"
  resources :ingressos, path: "ingressos"
end

app/models/peca.rb
class Peca < ApplicationRecord
    has_many :sessao, dependent: :destroy
    has_many :poltrona, through: :sessao
    has_many :area, through: :sessao
    has_many :ingresso, through: :sessao
    has_many :usuario, through: :ingresso
    
    #validates :nome, presence: true, uniqueness: true
    #validates :data, presence: true
    #validates :hora, presence: true
    validates :descricao, presence: true
end

app/controllers/pecas_controller.rb
class PecasController < ApplicationController
  before_action :set_peca, only: %i[ show edit update destroy ]

  # GET /pecas or /pecas.json
  def index
    @pecas = Peca.all
  end

  # GET /pecas/1 or /pecas/1.json
  def show
  end

  # GET /pecas/new
  def new
    @peca = Peca.new
  end

  # GET /pecas/1/edit
  def edit
  end

  # POST /pecas or /pecas.json
  def create
    @peca = Peca.new(peca_params)

    respond_to do |format|
      if @peca.save
        format.html { redirect_to @peca, notice: "Peca was successfully created." }
        format.json { render :show, status: :created, location: @peca }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @peca.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pecas/1 or /pecas/1.json
  def update
    respond_to do |format|
      if @peca.update(peca_params)
        format.html { redirect_to @peca, notice: "Peca was successfully updated." }
        format.json { render :show, status: :ok, location: @peca }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @peca.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pecas/1 or /pecas/1.json
  def destroy
    @peca.destroy!

    respond_to do |format|
      format.html { redirect_to pecas_path, status: :see_other, notice: "Peca was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_peca
      @peca = Peca.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def peca_params
      params.expect(peca: [ :titulo, :descricao, :duracao ])
    end
end

app/helpers/pecas_helper.rb
module PecasHelper
end

app/views/pecas/_form.html.erb
<%= form_with(model: peca) do |form| %>
  <% if peca.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(peca.errors.count, "error") %> prohibited this peca from being saved:</h2>

      <ul>
        <% peca.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :titulo, style: "display: block" %>
    <%= form.text_field :titulo %>
  </div>

  <div>
    <%= form.label :descricao, style: "display: block" %>
    <%= form.textarea :descricao %>
  </div>

  <div>
    <%= form.label :classificacao, style: "display: block" %>
    <%= form.text_field :classificacao %>
  </div>

  <div>
    <%= form.label :duracao, style: "display: block" %>
    <%= form.text_field :duracao %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/pecas/_peca.html.erb
<div id="<%= dom_id peca %>">
  <p>
    <strong>Titulo:</strong>
    <%= peca.titulo %>
  </p>

  <p>
    <strong>Descricao:</strong>
    <%= peca.descricao %>
  </p>

  <p>
    <strong>Classificacao:</strong>
    <%= peca.classificacao %>
  </p>

  <p>
    <strong>Duracao:</strong>
    <%= peca.duracao %>
  </p>

</div>

app/views/pecas/edit.html.erb
<% content_for :title, "Editing peca" %>

<h1>Editing peca</h1>

<%= render "form", peca: @peca %>

<br>

<div>
  <%= link_to "Show this peca", @peca %> |
  <%= link_to "Back to pecas", pecas_path %>
</div>

app/views/pecas/index.html.erb
<h1>Lista de Peças</h1>

<table>
  <thead>
    <tr>
      <th>Título</th>
      <th>Descrição</th>
      <th>Classificação</th>
      <th>Duração</th>
      <th colspan="3">Ações</th>
    </tr>
  </thead>

  <tbody>
    <% @pecas.each do |peca| %>
      <tr>
        <td><%= peca.titulo %></td>
        <td><%= peca.descricao %></td>
        <td><%= peca.classificacao %></td>
        <td><%= peca.duracao %></td>
        <td class="action-link"><%= link_to 'Mostrar', peca %></td>
        <td class="action-link"><%= link_to 'Editar', edit_peca_path(peca) %></td>
        <td class="action-link"><%= link_to 'Excluir', peca, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Nova Peça', new_peca_path, class: 'novo-link' %>

app/views/pecas/new.html.erb
<% content_for :title, "New peca" %>

<h1>New peca</h1>

<%= render "form", peca: @peca %>

<br>

<div>
  <%= link_to "Back to pecas", pecas_path %>
</div>

app/views/pecas/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @peca %>

<div>
  <%= link_to "Edit this peca", edit_peca_path(@peca) %> |
  <%= link_to "Back to pecas", pecas_path %>

  <%= button_to "Destroy this peca", @peca, method: :delete %>
</div>